// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetDevices():Promise<Array<main.Device>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;
